# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='pyppl_web',
    version='0.0.1',
    description='Web client to monitor pipeline processes for PyPPL',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "homepage": "https://github.com/pwwang/pyppl_web",
        "repository": "https://github.com/pwwang/pyppl_web"
    },
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    entry_points={"pyppl": ["pyppl_web = pyppl_web:PYPPLWEB"]},
    packages=['pyppl_web'],
    package_dir={"": "."},
    package_data={
        "pyppl_web": [
            "templates/semantic/*.html", "templates/semantic/static/css/*.css",
            "templates/semantic/static/css/themes/default/assets/fonts/*.eot",
            "templates/semantic/static/css/themes/default/assets/fonts/*.otf",
            "templates/semantic/static/css/themes/default/assets/fonts/*.svg",
            "templates/semantic/static/css/themes/default/assets/fonts/*.ttf",
            "templates/semantic/static/css/themes/default/assets/fonts/*.woff",
            "templates/semantic/static/css/themes/default/assets/fonts/*.woff2",
            "templates/semantic/static/css/themes/default/assets/images/*.png",
            "templates/semantic/static/images/*.png",
            "templates/semantic/static/js/*.js"
        ]
    },
    install_requires=[
        'cmdy', 'diot', 'flask==1.*,>=1.1.0', 'flask-socketio==4.*,>=4.3.0',
        'gevent-websocket==0.*,>=0.10.0', 'pyppl'
    ],
    extras_require={"dev": ["pytest", "pytest-cov"]},
)
